
# ~/.profile is not read by bash(1) if ~/.bash_profile or ~/.bash_login exist.
# So we source .profile ourselves, so that it doesn't matter which one is loaded.

if [ -f "$HOME/.profile" ]; then
  source "$HOME/.profile"
fi
