# Start profiling
# zmodload zsh/zprof

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac


# load all files from the .shellrc/zsh.d directory
if [ -d "$HOME/.shellrc/zsh.d" ]; then
  for file in "$HOME"/.shellrc/zsh.d/*.zsh(N); do
    source "$file"
  done

  # Support .local, not checked-in configs
  for file in "$HOME"/.shellrc/zsh.d/*.local(N); do
    source "$file"
  done
fi

# Shell agnostic items
if [ -d "$HOME/.shellrc/shell.d" ]; then
  for file in "$HOME"/.shellrc/shell.d/*.sh(N); do
    source "$file"
  done

  # Support .local, not checked-in configs
  for file in "$HOME"/.shellrc/shell.d/*.local(N); do
    source "$file"
  done
fi

# Stop profiling
# zprof